"""empty message

Revision ID: 2d8ac8f204bb
Revises: 2823d1ee2871
Create Date: 2023-07-01 16:20:24.578332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d8ac8f204bb'
down_revision = '2823d1ee2871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_competition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competition_data', schema=None) as batch_op:
        batch_op.drop_constraint('competition_data_dorsal_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition_data', schema=None) as batch_op:
        batch_op.create_unique_constraint('competition_data_dorsal_key', ['dorsal'])

    op.drop_table('category_competition')
    # ### end Alembic commands ###
