"""empty message

Revision ID: 39cc8d49cf29
Revises: fd64188489f9
Create Date: 2023-07-01 18:23:14.275425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39cc8d49cf29'
down_revision = 'fd64188489f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition', schema=None) as batch_op:
        batch_op.drop_column('location')

    # ### end Alembic commands ###
