"""empty message

Revision ID: 840e52039e32
Revises: 2d8ac8f204bb
Create Date: 2023-07-01 17:57:16.199006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840e52039e32'
down_revision = '2d8ac8f204bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_registration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_registration',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dorsal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('championship_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['championship_id'], ['championship.id'], name='tournament_registration_championship_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='tournament_registration_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tournament_registration_pkey'),
    sa.UniqueConstraint('dorsal', name='tournament_registration_dorsal_key')
    )
    # ### end Alembic commands ###
