"""empty message

Revision ID: 98139058346b
Revises: 
Create Date: 2023-06-24 14:13:06.249641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98139058346b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('championship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('competition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=True),
    sa.Column('fecha_celebracion', sa.Date(), nullable=True),
    sa.Column('hora_celebracion', sa.Time(), nullable=True),
    sa.Column('fecha_verificar_licencia', sa.Date(), nullable=True),
    sa.Column('hora_inicio_verificar_licencia', sa.Time(), nullable=True),
    sa.Column('hora_fin_verificar_licencia', sa.Time(), nullable=True),
    sa.Column('organizador', sa.String(length=30), nullable=True),
    sa.Column('limite_participacion', sa.Integer(), nullable=True),
    sa.Column('email_incidencias', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('surname', sa.String(length=80), nullable=True),
    sa.Column('dni', sa.String(length=9), nullable=True),
    sa.Column('uci_id', sa.Integer(), nullable=True),
    sa.Column('licencia', sa.String(length=9), nullable=True),
    sa.Column('federado', sa.Enum('Sí', 'No', name='federado'), nullable=True),
    sa.Column('sexo', sa.Enum('Hombre', 'Mujer', name='sexo'), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('club', sa.String(length=30), nullable=True),
    sa.Column('equipo', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('licencia'),
    sa.UniqueConstraint('uci_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=15), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('surname', sa.String(length=80), nullable=True),
    sa.Column('full_name', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=20), nullable=True),
    sa.Column('dni', sa.String(length=9), nullable=True),
    sa.Column('uci_id', sa.Integer(), nullable=True),
    sa.Column('licencia', sa.String(length=9), nullable=True),
    sa.Column('federado', sa.Enum('Sí', 'No', name='federado'), nullable=True),
    sa.Column('sexo', sa.Enum('Hombre', 'Mujer', name='sexo'), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('club', sa.String(length=30), nullable=True),
    sa.Column('equipo', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('licencia'),
    sa.UniqueConstraint('uci_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('registro_torneo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=True),
    sa.Column('championship_id', sa.Integer(), nullable=True),
    sa.Column('dorsal', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['championship_id'], ['championship.id'], ),
    sa.ForeignKeyConstraint(['rider_id'], ['rider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('inscripcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.Column('registro_torneo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.ForeignKeyConstraint(['registro_torneo_id'], ['registro_torneo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inscripcion')
    op.drop_table('team')
    op.drop_table('registro_torneo')
    op.drop_table('user')
    op.drop_table('rider')
    op.drop_table('competition')
    op.drop_table('club')
    op.drop_table('championship')
    op.drop_table('category')
    # ### end Alembic commands ###
