"""empty message

Revision ID: c4a83cc4d78b
Revises: 
Create Date: 2023-07-07 10:15:02.688909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4a83cc4d78b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('championship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('competition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('fecha_celebracion', sa.Date(), nullable=True),
    sa.Column('hora_celebracion', sa.Time(), nullable=True),
    sa.Column('location', sa.String(length=30), nullable=True),
    sa.Column('fecha_verificar_licencia', sa.Date(), nullable=True),
    sa.Column('organizador', sa.String(length=30), nullable=True),
    sa.Column('limite_participacion', sa.Integer(), nullable=True),
    sa.Column('email_incidencias', sa.String(length=30), nullable=True),
    sa.Column('championship_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['championship_id'], ['championship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('category_competition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('competition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('subname', sa.String(length=80), nullable=False),
    sa.Column('dni', sa.String(length=9), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('sexo', sa.Enum('Hombre', 'Mujer', name='sexo'), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('uci_id', sa.BigInteger(), nullable=True),
    sa.Column('licencia', sa.String(length=20), nullable=True),
    sa.Column('federado', sa.Enum('Sí', 'No', name='federado'), nullable=True),
    sa.Column('role', sa.Enum('User', 'Manager', 'Admin', name='role'), server_default='User', nullable=False),
    sa.Column('rider', sa.Enum('Yes', 'No', name='rider'), server_default='No', nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('licencia'),
    sa.UniqueConstraint('uci_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('competition_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dorsal', sa.Integer(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inscriptions')
    op.drop_table('competition_data')
    op.drop_table('user')
    op.drop_table('category_competition')
    op.drop_table('team')
    op.drop_table('competition')
    op.drop_table('club')
    op.drop_table('championship')
    op.drop_table('category')
    # ### end Alembic commands ###
