"""empty message

Revision ID: e0623f09e7b1
Revises: 
Create Date: 2023-06-19 17:19:39.200226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0623f09e7b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=True),
    sa.Column('fecha_celebracion', sa.Date(), nullable=True),
    sa.Column('hora_clebracion', sa.Time(), nullable=True),
    sa.Column('fecha_verificar_licencia', sa.Date(), nullable=True),
    sa.Column('hora_inicio_verificar_licencia', sa.Time(), nullable=True),
    sa.Column('hora_fin_verificar_licencia', sa.Time(), nullable=True),
    sa.Column('organizador', sa.String(length=30), nullable=True),
    sa.Column('limite_participacion', sa.Integer(), nullable=True),
    sa.Column('email_incidencia', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('championship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('competition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('categoria', sa.String(length=30), nullable=True),
    sa.Column('fecha_celebracion', sa.Date(), nullable=True),
    sa.Column('hora_clebracion', sa.Time(), nullable=True),
    sa.Column('fecha_verificar_licencia', sa.Date(), nullable=True),
    sa.Column('hora_inicio_verificar_licencia', sa.Time(), nullable=True),
    sa.Column('hora_fin_verificar_licencia', sa.Time(), nullable=True),
    sa.Column('organizador', sa.String(length=30), nullable=True),
    sa.Column('limite_participacion', sa.Integer(), nullable=True),
    sa.Column('email_incidencia', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dorsal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('Dorsal', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('riders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('surname', sa.String(length=80), nullable=True),
    sa.Column('dni', sa.String(length=9), nullable=True),
    sa.Column('uci_id', sa.Integer(), nullable=True),
    sa.Column('licencia', sa.String(length=9), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('club', sa.String(length=30), nullable=True),
    sa.Column('equipo', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('licencia'),
    sa.UniqueConstraint('uci_id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=15), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('surname', sa.String(length=80), nullable=True),
    sa.Column('nick', sa.String(length=20), nullable=True),
    sa.Column('dni', sa.String(length=9), nullable=True),
    sa.Column('uci_id', sa.Integer(), nullable=True),
    sa.Column('licencia', sa.String(length=9), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('club', sa.String(length=30), nullable=True),
    sa.Column('equipo', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('licencia'),
    sa.UniqueConstraint('uci_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('team')
    op.drop_table('riders')
    op.drop_table('dorsal')
    op.drop_table('competition')
    op.drop_table('club')
    op.drop_table('championship')
    op.drop_table('category')
    op.drop_table('calendar')
    # ### end Alembic commands ###
