"""empty message

Revision ID: fd64188489f9
Revises: 1d3765413fe5
Create Date: 2023-07-01 18:20:59.292890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fd64188489f9'
down_revision = '1d3765413fe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition', schema=None) as batch_op:
        batch_op.drop_column('hora_fin_verificar_licencia')
        batch_op.drop_column('hora_inicio_verificar_licencia')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora_inicio_verificar_licencia', postgresql.TIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hora_fin_verificar_licencia', postgresql.TIME(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
